### ISSUE TITLE
interpolated ruby strings no longer works at all

### ISSUE THREAD

**Issue by canoeberry** [facelessuser/BracketHighlighter#518]
## Description

In ruby, interpolated strings no longer work.

If I put the cursor inside the double quoted string (but not the #{} part) and select Jump to Left Bracket from the menu, the cursor ends up by the def. And in fact, the 'def' and 'end' tags are highlighted:

![Screenshot 2019-03-25 at 08 40 59](https://user-images.githubusercontent.com/520067/54905857-e64a2780-4ed9-11e9-8fa3-f9ade6bfd370.png)

If I put the cursor at the end of the interpolated string, the def/end are not highlighted but Jump to Left Bracket behaves the same, moving to the 'def':

![Screenshot 2019-03-25 at 08 41 12](https://user-images.githubusercontent.com/520067/54905856-e64a2780-4ed9-11e9-8638-a9729eb89e85.png)

Anywhere inside the single quoted string works fine, taking me to the left single quote as expected, and the left and right single quotes are what's highlighted. Also, double quoted strings work fine if there is no interpolation in them at all:

![Screenshot 2019-03-25 at 08 42 05](https://user-images.githubusercontent.com/520067/54905855-e64a2780-4ed9-11e9-962d-07a486251e5e.png)

When I look at the scopes, I get the following values:

* when cursor is inside the text 'Current user: ' I am told [15 bytes: source.ruby.rails string.quoted.double.ruby ]
* when cursor is between the } and the " I am told [1 bytes: source.ruby.rails string.quoted.double.ruby punctuation.definition.string.end.ruby ]
* when cursor is anywhere within the single quoted string, I am told [33 bytes: source.ruby.rails string.quoted.single.ruby]

I am pretty sure this all worked until I get the latest version of the stable Sublime, which for me is version 3.2 (3200).

I am worried there's no solution. I am puzzled by those scope responses above, which show the portions of the interpolated string that are actual string are just pieces of the full string and not the entire thing. But I don't really know how this plugin works.

## Support Info

...

> Run the following command from the menu: `Preferences->Package Settings->BracketHighlighter->Support Info`.  Post the result here.

- ST ver.: 3200
- Platform: osx
- Arch: x64
- Plugin ver.: 2.27.2
- Install via PC: False
- mdpopups ver.: 3.4.0
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment]
1. To help people, some copy/pastable examples are required. I'm personally not a big fan of recreating issues by retyping code I see in images, though images are useful at times to show behavior. So if you can post some plain text, copy/pastable examples as well, that would be very helpful.

2. Sublime Text has overhauled a number of their syntaxes, so it doesn't surprise me that interpolated strings may have become broken.

3. I don't use Ruby, so generally, I would require a pull request from the community, preferably from a Ruby user who understands Ruby, to get this fixed. I do occasionally take a look at cases in languages I don't specifically use, but it usually requires copy/pastable examples 😉 .

FYI, I noticed your backrefs version looks old, I'd try running `Package Control: Satisfy Dependencies` to update it.  It probably isn't contributing to issues, but I'd probably do it to pick up bug fixes etc.

**Comment by canoeberry** [comment]
Sorry for writing such a bad bug report. I had my own copy of your plugin but I thought I updated it but now I think I didn't do that properly based on what you said.

And I have now deleted my copy and gone back to the latest version in package control, and am still seeing the same problem. If you're willing maybe you could give me a hint about what the syntax is now doing wrong.

```  #
  # Return top-level array in JSON data or [].
  #
  def array(name, required = false, from: nil)
    from ||= @json_data
    array = from[name]
    if array
      array
    elsif required
      raise ArgumentError, "Missing data in JSON file: #{name} and more string here "
    else
      []
    end
  end
```

Anywhere within the interpolated string fails to recognise the extent of the scope, except if the cursor is in the #{name} part of the string.

**Comment by canoeberry** [comment]
I seem to sort of fixed it by editing the Ruby Syntax. The interpolated-ruby pattern was using 'clear_scopes: 1' and I just thought that might be a problem, and it was.

However I have no idea what I have done by deleting it.

I figured that clearing the parent scope might be causing the problem but it's hard to tell.

```yaml
    # double quoted string (allows for interpolation)
    - match: '"'
      scope: punctuation.definition.string.begin.ruby
      push:
        - meta_scope: string.quoted.double.ruby
        - match: '"'
          scope: punctuation.definition.string.end.ruby
          pop: true
        - include: interpolated-ruby
        - include: escaped-char
        - include: string-placeholder
```

And here's what I changed interpolated-string to:

```yaml
  interpolated-ruby:
    - match: '#\{'
      scope: punctuation.section.interpolation.begin.ruby
      push:
        - clear_scopes: 1       <----------- DELETED THIS LINE
        - meta_scope: meta.interpolation
        - meta_content_scope: source.ruby.embedded
        - match: '\}'
          scope: punctuation.section.interpolation.end.ruby
          pop: true
        - include: nest-curly-expressions
        - include: expressions
```
No idea what this means. If you clear the parent scope from the stack, how does it re-establish the double quoted string scope after interpolation is finished?

Oh my, in over my head.
